- name: Base server setup
  hosts: all
  become: true
  roles:
    - role: devsec.hardening.os_hardening
      tags: os
      vars:
        os_ignore_users: ["{{ ansible_user }}"]
        sysctl_overwrite:
          net.ipv4.ip_forward: 1
          net.ipv6.conf.all.forwarding: 1
          net.ipv6.conf.all.disable_ipv6: 0
          net.ipv6.conf.default.disable_ipv6: 0

    - role: fish
      become: false
      tags: [fish, packages]

    - role: geerlingguy.docker
      tags: [docker, packages]

  tasks:
    - name: install htop
      ansible.builtin.package:
        name: htop
        state: present
      tags: [htop, packages]

    - name: install git
      ansible.builtin.package:
        name: git
        state: present
      tags: [git, packages]
