# Generated by Django 6.0.2 on 2026-02-25 06:49

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_gallerypage_options_alter_gallerypage_body_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerypage',
            name='video_collection',
            field=wagtail.fields.StreamField([('videos', 1)], blank=True, block_lookup={0: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 1: ('wagtail.blocks.ListBlock', (0,), {'label': 'Коллекция видео'})}),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='collection',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('name__in', ['Root']), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.collection', verbose_name='Коллекция изображений'),
        ),
    ]
