# Generated by Django 6.0.2 on 2026-02-25 07:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_gallerypage_video_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypage',
            name='video_collection',
            field=wagtail.fields.StreamField([('videos', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RawHTMLBlock', (), {}), 1: ('wagtail.blocks.ListBlock', (0,), {'label': 'Коллекция видео'})}),
        ),
    ]
