# Generated by Django 6.0.2 on 2026-02-25 07:40

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_gallerypage_video_collection'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypage',
            name='video_collection',
            field=wagtail.fields.StreamField([('videos', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RawHTMLBlock', (), {}), 1: ('wagtail.blocks.ListBlock', (0,), {'collapsed': True, 'label': 'Коллекция видео'})}),
        ),
        migrations.CreateModel(
            name='RoomPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.TextField(blank=True, verbose_name='Описание')),
                ('body', wagtail.fields.StreamField([('heading_block', 2), ('paragraph_block', 3), ('image_block', 6), ('block_quote', 12), ('embed_block', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Select a header size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'description': 'A rich text paragraph', 'icon': 'pilcrow', 'preview_value': '\n            <h2>Our bread pledge</h2>\n            <p>As a bakery, <b>breads</b> have <i>always</i> been in our hearts.\n            <a href="https://en.wikipedia.org/wiki/Staple_food">Staple foods</a>\n            are essential for society, and – bread is the tastiest of all.\n            We love to transform batters and doughs into baked goods with a firm\n            dry crust and fluffy center.</p>\n            ', 'template': 'blocks/paragraph_block.html'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('attribution', 5)]], {}), 7: ('wagtail.blocks.TextBlock', (), {}), 8: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'e.g. Mary Berry', 'required': False}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('highlight', 'Highlight')], 'required': False}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('large', 'Large')], 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('theme', 9), ('text_size', 10)]], {'collapsed': True}), 12: ('wagtail.blocks.StructBlock', [[('text', 7), ('attribute_name', 8), ('settings', 11)]], {}), 13: ('wagtail.embeds.blocks.EmbedBlock', (), {'description': 'An embedded video or other media', 'help_text': 'Insert an embed URL e.g https://www.youtube.com/watch?v=SGJFWirQ3ks', 'icon': 'media', 'preview_template': 'base/preview/static_embed_block.html', 'preview_value': 'https://www.youtube.com/watch?v=mwrGSfiB1Mg', 'template': 'blocks/embed_block.html'})}, verbose_name='Содержимое')),
                ('video_collection', wagtail.fields.StreamField([('videos', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RawHTMLBlock', (), {}), 1: ('wagtail.blocks.ListBlock', (0,), {'collapsed': True, 'label': 'Коллекция видео'})})),
                ('room_size', models.TextField(help_text='Пример: 14-20м2', verbose_name='Размер номера')),
                ('adults', models.PositiveIntegerField(verbose_name='Количество взрослых')),
                ('children', models.PositiveIntegerField(default=0, verbose_name='Количество детей')),
                ('beds', models.PositiveIntegerField(verbose_name='Количество спальных мест')),
                ('collection', models.ForeignKey(blank=True, limit_choices_to=models.Q(('name__in', ['Root']), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.collection', verbose_name='Коллекция изображений')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Титульное изображение')),
            ],
            options={
                'verbose_name': 'Номер',
            },
            bases=('wagtailcore.page',),
        ),
    ]
