# Generated by Django 6.0.2 on 2026-02-25 08:07

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_gallerypage_features_roompage_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypage',
            name='features',
            field=wagtail.fields.StreamField([('feature', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'verbose_name': 'Текст'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: fa-bed, fa-wifi. https://fontawesome.com/search?q=cat&ic=free-collection', 'max_length': 50, 'verbose_name': 'Иконка'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('icon', 1)]], {})}, verbose_name='Особенности объекта'),
        ),
        migrations.AlterField(
            model_name='roompage',
            name='features',
            field=wagtail.fields.StreamField([('feature', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'verbose_name': 'Текст'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: fa-bed, fa-wifi. https://fontawesome.com/search?q=cat&ic=free-collection', 'max_length': 50, 'verbose_name': 'Иконка'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('icon', 1)]], {})}, verbose_name='Особенности объекта'),
        ),
    ]
