# Generated by Django 6.0.2 on 2026-02-25 08:56

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_gallerypage_body_alter_roompage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypage',
            name='video_collection',
            field=wagtail.fields.StreamField([('videos', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RawHTMLBlock', (), {}), 1: ('wagtail.blocks.ListBlock', (0,), {'collapsed': True, 'label': 'Код видео'})}, verbose_name='Коллекция видео'),
        ),
        migrations.AlterField(
            model_name='roompage',
            name='video_collection',
            field=wagtail.fields.StreamField([('videos', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RawHTMLBlock', (), {}), 1: ('wagtail.blocks.ListBlock', (0,), {'collapsed': True, 'label': 'Код видео'})}, verbose_name='Коллекция видео'),
        ),
    ]
