# Generated by Django 6.0.2 on 2026-02-25 09:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_gallerypage_body_alter_roompage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypage',
            name='body',
            field=wagtail.fields.StreamField([('heading_block', 2), ('paragraph_block', 3), ('html_block', 4), ('image_block', 7), ('block_quote', 13), ('embed_block', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'required': True, 'verbose_name': 'Текст'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Выберите заголовок'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'required': False, 'verbose_name': 'Размер'}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Параграф', 'template': 'blocks/paragraph_block.html'}), 4: ('wagtail_html_editor.blocks.EnhancedHTMLBlock', (), {'label': 'Код HTML'}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 5), ('caption', 6), ('attribution', 6)]], {}), 8: ('wagtail.blocks.TextBlock', (), {}), 9: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'e.g. Mary Berry', 'required': False}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('highlight', 'Highlight')], 'required': False}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('large', 'Large')], 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('theme', 10), ('text_size', 11)]], {'collapsed': True}), 13: ('wagtail.blocks.StructBlock', [[('text', 8), ('attribute_name', 9), ('settings', 12)]], {}), 14: ('wagtail.embeds.blocks.EmbedBlock', (), {'icon': 'media', 'label': 'Встраиваемое видео', 'preview_template': 'base/preview/static_embed_block.html', 'template': 'blocks/embed_block.html'})}, verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='roompage',
            name='body',
            field=wagtail.fields.StreamField([('heading_block', 2), ('paragraph_block', 3), ('html_block', 4), ('image_block', 7), ('block_quote', 13), ('embed_block', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'required': True, 'verbose_name': 'Текст'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Выберите заголовок'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'required': False, 'verbose_name': 'Размер'}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Параграф', 'template': 'blocks/paragraph_block.html'}), 4: ('wagtail_html_editor.blocks.EnhancedHTMLBlock', (), {'label': 'Код HTML'}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 5), ('caption', 6), ('attribution', 6)]], {}), 8: ('wagtail.blocks.TextBlock', (), {}), 9: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'e.g. Mary Berry', 'required': False}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('highlight', 'Highlight')], 'required': False}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('large', 'Large')], 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('theme', 10), ('text_size', 11)]], {'collapsed': True}), 13: ('wagtail.blocks.StructBlock', [[('text', 8), ('attribute_name', 9), ('settings', 12)]], {}), 14: ('wagtail.embeds.blocks.EmbedBlock', (), {'icon': 'media', 'label': 'Встраиваемое видео', 'preview_template': 'base/preview/static_embed_block.html', 'template': 'blocks/embed_block.html'})}, verbose_name='Содержимое'),
        ),
    ]
