# Generated by Django 6.0.2 on 2026-02-25 10:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_gallerypage_body_alter_roompage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypage',
            name='body',
            field=wagtail.fields.StreamField([('heading_block', 2), ('paragraph_block', 3), ('html_block', 4), ('image_block', 8), ('block_quote', 14), ('embed_block', 15)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'label': 'Текст', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Выберите заголовок'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'label': 'Размер', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Параграф', 'template': 'blocks/paragraph_block.html'}), 4: ('wagtail_html_editor.blocks.EnhancedHTMLBlock', (), {'label': 'Код HTML'}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Автор', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('image', 5), ('caption', 6), ('attribution', 7)]], {}), 9: ('wagtail.blocks.TextBlock', (), {'label': 'Текст'}), 10: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'e.g. Mary Berry', 'required': False}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('highlight', 'Highlight')], 'required': False}), 12: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('large', 'Large')], 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('theme', 11), ('text_size', 12)]], {'collapsed': True}), 14: ('wagtail.blocks.StructBlock', [[('text', 9), ('attribute_name', 10), ('settings', 13)]], {}), 15: ('wagtail.embeds.blocks.EmbedBlock', (), {'icon': 'media', 'label': 'Встраиваемое видео', 'preview_template': 'base/preview/static_embed_block.html', 'template': 'blocks/embed_block.html'})}, verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='features',
            field=wagtail.fields.StreamField([('feature', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 255}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: fa-bed, fa-wifi. https://fontawesome.com/search?q=cat&ic=free-collection', 'label': 'Иконка', 'max_length': 50}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('icon', 1)]], {})}, verbose_name='Особенности объекта'),
        ),
        migrations.AlterField(
            model_name='roompage',
            name='body',
            field=wagtail.fields.StreamField([('heading_block', 2), ('paragraph_block', 3), ('html_block', 4), ('image_block', 8), ('block_quote', 14), ('embed_block', 15)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'label': 'Текст', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Выберите заголовок'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'label': 'Размер', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Параграф', 'template': 'blocks/paragraph_block.html'}), 4: ('wagtail_html_editor.blocks.EnhancedHTMLBlock', (), {'label': 'Код HTML'}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Автор', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('image', 5), ('caption', 6), ('attribution', 7)]], {}), 9: ('wagtail.blocks.TextBlock', (), {'label': 'Текст'}), 10: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'e.g. Mary Berry', 'required': False}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('highlight', 'Highlight')], 'required': False}), 12: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('large', 'Large')], 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('theme', 11), ('text_size', 12)]], {'collapsed': True}), 14: ('wagtail.blocks.StructBlock', [[('text', 9), ('attribute_name', 10), ('settings', 13)]], {}), 15: ('wagtail.embeds.blocks.EmbedBlock', (), {'icon': 'media', 'label': 'Встраиваемое видео', 'preview_template': 'base/preview/static_embed_block.html', 'template': 'blocks/embed_block.html'})}, verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='roompage',
            name='features',
            field=wagtail.fields.StreamField([('feature', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 255}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: fa-bed, fa-wifi. https://fontawesome.com/search?q=cat&ic=free-collection', 'label': 'Иконка', 'max_length': 50}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('icon', 1)]], {})}, verbose_name='Особенности объекта'),
        ),
    ]
