# Generated by Django 6.0.2 on 2026-02-25 10:59

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_gallerypage_body_alter_gallerypage_features_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.TextField(blank=True, verbose_name='Описание')),
                ('body', wagtail.fields.StreamField([('heading_block', 2), ('paragraph_block', 3), ('html_block', 4), ('image_block', 8), ('block_quote', 14), ('embed_block', 15)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'label': 'Текст', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Выберите заголовок'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'label': 'Размер', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Параграф', 'template': 'blocks/paragraph_block.html'}), 4: ('wagtail_html_editor.blocks.EnhancedHTMLBlock', (), {'label': 'Код HTML'}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Автор', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('image', 5), ('caption', 6), ('attribution', 7)]], {}), 9: ('wagtail.blocks.TextBlock', (), {'label': 'Текст'}), 10: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'e.g. Mary Berry', 'required': False}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('highlight', 'Highlight')], 'required': False}), 12: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('large', 'Large')], 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('theme', 11), ('text_size', 12)]], {'collapsed': True}), 14: ('wagtail.blocks.StructBlock', [[('text', 9), ('attribute_name', 10), ('settings', 13)]], {}), 15: ('wagtail.embeds.blocks.EmbedBlock', (), {'icon': 'media', 'label': 'Встраиваемое видео', 'preview_template': 'base/preview/static_embed_block.html', 'template': 'blocks/embed_block.html'})}, verbose_name='Содержимое')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Титульное изображение')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
