# Generated by Django 6.0.2 on 2026-02-25 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_standardpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standardpage',
            options={'verbose_name': 'Страница'},
        ),
    ]
