# Generated by Django 6.0.2 on 2026-02-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_standardpage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_short', models.CharField(max_length=100, verbose_name='Адрес (короткий)')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('social_vk', models.URLField(blank=True, verbose_name='VK URL')),
                ('social_ok', models.URLField(blank=True, verbose_name='OK URL')),
                ('social_rutube', models.URLField(blank=True, verbose_name='Rutube URL')),
                ('social_yandex', models.URLField(blank=True, verbose_name='Yandex URL')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
