# Generated by Django 6.0.2 on 2026-02-25 13:44

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_genericsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genericsettings',
            options={'verbose_name': 'Контакты'},
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='features',
            field=wagtail.fields.StreamField([('feature', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 255}), 1: ('wagtail.blocks.CharBlock', (), {'blank': True, 'help_text': 'Например: fa-bed, fa-wifi. https://fontawesome.com/search?q=cat&ic=free-collection', 'label': 'Иконка', 'max_length': 50}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('icon', 1)]], {})}, verbose_name='Особенности объекта'),
        ),
        migrations.AlterField(
            model_name='roompage',
            name='features',
            field=wagtail.fields.StreamField([('feature', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 255}), 1: ('wagtail.blocks.CharBlock', (), {'blank': True, 'help_text': 'Например: fa-bed, fa-wifi. https://fontawesome.com/search?q=cat&ic=free-collection', 'label': 'Иконка', 'max_length': 50}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('icon', 1)]], {})}, verbose_name='Особенности объекта'),
        ),
    ]
