# Generated by Django 6.0.2 on 2026-02-25 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_genericsettings_options_and_more'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='bg_video_size_l',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='wagtaildocs.document', verbose_name='Фоновое видео (большое)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='bg_video_size_m',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Фоновое видео (среднее)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='bg_video_size_s',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Фоновое видео (малое)'),
        ),
    ]
