# Generated by Django 6.0.2 on 2026-02-25 14:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_homepage_bg_video_size_l_homepage_bg_video_size_m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypage',
            name='features',
            field=wagtail.fields.StreamField([('feature', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 255}), 1: ('wagtail.blocks.CharBlock', (), {'blank': True, 'help_text': 'Например: fa-bed, fa-wifi. https://fontawesome.com/search?q=cat&ic=free-collection', 'label': 'Иконка', 'max_length': 50}), 2: ('wagtail.blocks.IntegerBlock', (), {'blank': True, 'label': 'Счетчик', 'max_length': 255, 'min_value': 1}), 3: ('wagtail.blocks.StructBlock', [[('text', 0), ('icon', 1), ('counter', 2)]], {})}, verbose_name='Особенности объекта'),
        ),
        migrations.AlterField(
            model_name='roompage',
            name='features',
            field=wagtail.fields.StreamField([('feature', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 255}), 1: ('wagtail.blocks.CharBlock', (), {'blank': True, 'help_text': 'Например: fa-bed, fa-wifi. https://fontawesome.com/search?q=cat&ic=free-collection', 'label': 'Иконка', 'max_length': 50}), 2: ('wagtail.blocks.IntegerBlock', (), {'blank': True, 'label': 'Счетчик', 'max_length': 255, 'min_value': 1}), 3: ('wagtail.blocks.StructBlock', [[('text', 0), ('icon', 1), ('counter', 2)]], {})}, verbose_name='Особенности объекта'),
        ),
    ]
