# Generated by Django 6.0.2 on 2026-02-25 14:31

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_gallerypage_features_alter_roompage_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypage',
            name='features',
            field=wagtail.fields.StreamField([('feature', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 255}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: fa-bed, fa-wifi. https://fontawesome.com/search?q=cat&ic=free-collection', 'label': 'Иконка', 'max_length': 50, 'required': False}), 2: ('wagtail.blocks.IntegerBlock', (), {'label': 'Счетчик', 'max_length': 255, 'min_value': 1, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('text', 0), ('icon', 1), ('counter', 2)]], {})}, verbose_name='Особенности объекта'),
        ),
        migrations.AlterField(
            model_name='roompage',
            name='features',
            field=wagtail.fields.StreamField([('feature', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 255}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: fa-bed, fa-wifi. https://fontawesome.com/search?q=cat&ic=free-collection', 'label': 'Иконка', 'max_length': 50, 'required': False}), 2: ('wagtail.blocks.IntegerBlock', (), {'label': 'Счетчик', 'max_length': 255, 'min_value': 1, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('text', 0), ('icon', 1), ('counter', 2)]], {})}, verbose_name='Особенности объекта'),
        ),
    ]
