# Generated by Django 6.0.2 on 2026-02-25 14:52

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_homepage_activities_homepage_facilities_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_section_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Раздел 1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_1_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок раздела 1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Раздел 2'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_2_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок раздела 2'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Раздел 3'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_3_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок раздела 3'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='facilities',
            field=wagtail.fields.StreamField([('feature', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 255}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: fa-bed, fa-wifi. https://fontawesome.com/search?q=cat&ic=free-collection', 'label': 'Иконка', 'max_length': 50, 'required': False}), 2: ('wagtail.blocks.IntegerBlock', (), {'label': 'Счетчик', 'max_length': 255, 'min_value': 1, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('text', 0), ('icon', 1), ('counter', 2)]], {'label': 'Услуга'})}, verbose_name='Услуги/инфраструктура отеля'),
        ),
    ]
