# Generated by Django 6.0.2 on 2026-02-25 15:07

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_homepage_featured_section_1_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_photos',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('name__in', ['Root']), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.collection', verbose_name='Избранные изображений'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='reviews',
            field=wagtail.fields.StreamField([('feature', 2)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'label': 'Текст'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Автор', 'max_length': 255}), 2: ('wagtail.blocks.StructBlock', [[('review', 0), ('author', 1)]], {'label': 'Отзыв'})}, verbose_name='Отзывы клиентов'),
        ),
    ]
