# Generated by Django 6.0.2 on 2026-02-25 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_homepage_featured_photos_homepage_reviews'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='featured_photos',
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_photos_1',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('name__in', ['Root']), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.collection', verbose_name='Избранные изображения 1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_photos_2',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('name__in', ['Root']), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.collection', verbose_name='Избранные изображения 2'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_1',
            field=models.TextField(blank=True, verbose_name='Заголовок 1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_2',
            field=models.TextField(blank=True, verbose_name='Заголовок 2'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='text_1',
            field=models.TextField(blank=True, verbose_name='Текст 1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='text_2',
            field=models.TextField(blank=True, verbose_name='Текст 2'),
        ),
    ]
