# Generated by Django 6.0.2 on 2026-02-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_remove_homepage_featured_photos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='header_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок 1'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='header_2',
            field=models.TextField(blank=True, max_length=255, verbose_name='Заголовок 2'),
        ),
    ]
