# Generated by Django 6.0.2 on 2026-02-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_homepage_header_1_alter_homepage_header_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='header_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок 2'),
        ),
    ]
