# Generated by Django 6.0.2 on 2026-02-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_homepage_header_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericsettings',
            name='address',
            field=models.TextField(max_length=255, verbose_name='Адрес'),
        ),
    ]
