# Generated by Django 6.0.2 on 2026-02-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_genericsettings_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericsettings',
            name='book_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на бронирование'),
        ),
    ]
