# Generated by Django 6.0.2 on 2026-02-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_genericsettings_book_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericsettings',
            name='book_link_text',
            field=models.CharField(blank=True, verbose_name='Текст ссылки на бронирование'),
        ),
    ]
