# Generated by Django 6.0.2 on 2026-02-27 20:55

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_roomlistpage_alter_gallerylistpage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypage',
            name='video_collection',
            field=wagtail.fields.StreamField([('videos', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RawHTMLBlock', (), {'label': 'Код видео'})}, verbose_name='Коллекция видео'),
        ),
        migrations.AlterField(
            model_name='roompage',
            name='video_collection',
            field=wagtail.fields.StreamField([('videos', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RawHTMLBlock', (), {'label': 'Код видео'})}, verbose_name='Коллекция видео'),
        ),
    ]
