# Generated by Django 6.0.2 on 2026-02-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_alter_gallerypage_video_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerylistpage',
            name='header',
            field=models.TextField(blank=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='gallerylistpage',
            name='introduction_1',
            field=models.TextField(blank=True, verbose_name='Описание 1'),
        ),
        migrations.AddField(
            model_name='gallerylistpage',
            name='introduction_2',
            field=models.TextField(blank=True, verbose_name='Описание 2'),
        ),
        migrations.AddField(
            model_name='roomlistpage',
            name='header',
            field=models.TextField(blank=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='roomlistpage',
            name='introduction_1',
            field=models.TextField(blank=True, verbose_name='Описание 1'),
        ),
        migrations.AddField(
            model_name='roomlistpage',
            name='introduction_2',
            field=models.TextField(blank=True, verbose_name='Описание 2'),
        ),
    ]
