# Generated by Django 6.0.2 on 2026-02-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_gallerylistpage_header_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerylistpage',
            name='header',
            field=models.CharField(blank=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='roomlistpage',
            name='header',
            field=models.CharField(blank=True, verbose_name='Заголовок'),
        ),
    ]
