# Generated by Django 6.0.2 on 2026-02-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alter_gallerylistpage_header_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericsettings',
            name='specials_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на специальные предложения'),
        ),
        migrations.AddField(
            model_name='genericsettings',
            name='specials_link_text',
            field=models.CharField(blank=True, verbose_name='Текст ссылки на специальные предложения'),
        ),
    ]
