# Generated by Django 6.0.2 on 2026-02-28 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_genericsettings_specials_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genericsettings',
            options={'verbose_name': 'Проект'},
        ),
    ]
