# Generated by Django 6.0.2 on 2026-02-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_alter_genericsettings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericsettings',
            name='book_link',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Ссылка на бронирование'),
        ),
    ]
