# Generated by Django 6.0.2 on 2026-02-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_alter_genericsettings_book_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericsettings',
            name='book_link',
            field=models.TextField(blank=True, verbose_name='Ссылка на бронирование'),
        ),
    ]
