# Generated by Django 6.0.2 on 2026-03-03 12:19

import django.db.models.deletion
import wagtail.fields
import wagtailcache.cache
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_alter_genericsettings_book_link'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerylistpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Титульное изображение'),
        ),
        migrations.AddField(
            model_name='roomlistpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Титульное изображение'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='body',
            field=wagtail.fields.StreamField([('heading_block', 2), ('paragraph_block', 3), ('html_block', 4), ('images_block', 6), ('image_block', 10), ('block_quote', 16), ('embed_block', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'label': 'Текст', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Выберите заголовок'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'label': 'Размер', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Параграф', 'template': 'blocks/paragraph_block.html'}), 4: ('wagtail_html_editor.blocks.EnhancedHTMLBlock', (), {'label': 'Код HTML'}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 6: ('wagtail.blocks.ListBlock', (5,), {'icon': 'image', 'label': 'Галерея', 'max_num': 3, 'min_num': 1, 'template': 'blocks/images_block.html'}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение с подписью', 'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись', 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Автор', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('image', 7), ('caption', 8), ('attribution', 9)]], {}), 11: ('wagtail.blocks.TextBlock', (), {'label': 'Текст'}), 12: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'e.g. Mary Berry', 'required': False}), 13: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('highlight', 'Highlight')], 'required': False}), 14: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('large', 'Large')], 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('theme', 13), ('text_size', 14)]], {'collapsed': True}), 16: ('wagtail.blocks.StructBlock', [[('text', 11), ('attribute_name', 12), ('settings', 15)]], {}), 17: ('wagtail.embeds.blocks.EmbedBlock', (), {'icon': 'media', 'label': 'Встраиваемое видео', 'preview_template': 'base/preview/static_embed_block.html', 'template': 'blocks/embed_block.html'})}, verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='roompage',
            name='body',
            field=wagtail.fields.StreamField([('heading_block', 2), ('paragraph_block', 3), ('html_block', 4), ('images_block', 6), ('image_block', 10), ('block_quote', 16), ('embed_block', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'label': 'Текст', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Выберите заголовок'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'label': 'Размер', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Параграф', 'template': 'blocks/paragraph_block.html'}), 4: ('wagtail_html_editor.blocks.EnhancedHTMLBlock', (), {'label': 'Код HTML'}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 6: ('wagtail.blocks.ListBlock', (5,), {'icon': 'image', 'label': 'Галерея', 'max_num': 3, 'min_num': 1, 'template': 'blocks/images_block.html'}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение с подписью', 'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись', 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Автор', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('image', 7), ('caption', 8), ('attribution', 9)]], {}), 11: ('wagtail.blocks.TextBlock', (), {'label': 'Текст'}), 12: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'e.g. Mary Berry', 'required': False}), 13: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('highlight', 'Highlight')], 'required': False}), 14: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('large', 'Large')], 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('theme', 13), ('text_size', 14)]], {'collapsed': True}), 16: ('wagtail.blocks.StructBlock', [[('text', 11), ('attribute_name', 12), ('settings', 15)]], {}), 17: ('wagtail.embeds.blocks.EmbedBlock', (), {'icon': 'media', 'label': 'Встраиваемое видео', 'preview_template': 'base/preview/static_embed_block.html', 'template': 'blocks/embed_block.html'})}, verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.fields.StreamField([('heading_block', 2), ('paragraph_block', 3), ('html_block', 4), ('images_block', 6), ('image_block', 10), ('block_quote', 16), ('embed_block', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'label': 'Текст', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Выберите заголовок'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'label': 'Размер', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Параграф', 'template': 'blocks/paragraph_block.html'}), 4: ('wagtail_html_editor.blocks.EnhancedHTMLBlock', (), {'label': 'Код HTML'}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 6: ('wagtail.blocks.ListBlock', (5,), {'icon': 'image', 'label': 'Галерея', 'max_num': 3, 'min_num': 1, 'template': 'blocks/images_block.html'}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение с подписью', 'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись', 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Автор', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('image', 7), ('caption', 8), ('attribution', 9)]], {}), 11: ('wagtail.blocks.TextBlock', (), {'label': 'Текст'}), 12: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'e.g. Mary Berry', 'required': False}), 13: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('highlight', 'Highlight')], 'required': False}), 14: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('large', 'Large')], 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('theme', 13), ('text_size', 14)]], {'collapsed': True}), 16: ('wagtail.blocks.StructBlock', [[('text', 11), ('attribute_name', 12), ('settings', 15)]], {}), 17: ('wagtail.embeds.blocks.EmbedBlock', (), {'icon': 'media', 'label': 'Встраиваемое видео', 'preview_template': 'base/preview/static_embed_block.html', 'template': 'blocks/embed_block.html'})}, verbose_name='Содержимое'),
        ),
        migrations.CreateModel(
            name='StandardListPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('header', models.CharField(blank=True, verbose_name='Заголовок')),
                ('introduction_1', models.TextField(blank=True, verbose_name='Описание 1')),
                ('introduction_2', models.TextField(blank=True, verbose_name='Описание 2')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Титульное изображение')),
            ],
            options={
                'verbose_name': 'Список страниц',
            },
            bases=(wagtailcache.cache.WagtailCacheMixin, 'wagtailcore.page'),
        ),
    ]
