# Generated by Django 6.0.2 on 2026-03-25 06:38

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_gallerylistpage_image_roomlistpage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='featured_photos_3',
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_photos_footer',
            field=wagtail.fields.StreamField([('gallery', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('alt_text', 1), ('caption', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {'label': 'Изображения', 'min_num': 1}), 4: ('wagtail.blocks.StructBlock', [[('images', 3)]], {})}, null=True, verbose_name='Изображения в подвале'),
        ),
    ]
