# Generated by Django 6.0.2 on 2026-03-25 07:55

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_remove_homepage_featured_photos_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_photos_middle',
            field=wagtail.fields.StreamField([('gallery', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Alt-текст', 'max_length': 255, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('alt_text', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {'label': 'Изображения', 'min_num': 1}), 4: ('wagtail.blocks.StructBlock', [[('images', 3)]], {'label': 'Галерея'})}, null=True, verbose_name='Изображения под шапкой'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='featured_photos_footer',
            field=wagtail.fields.StreamField([('gallery', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Alt-текст', 'max_length': 255, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('alt_text', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {'label': 'Изображения', 'min_num': 1}), 4: ('wagtail.blocks.StructBlock', [[('images', 3)]], {'label': 'Галерея'})}, null=True, verbose_name='Изображения в подвале'),
        ),
    ]
