# Generated by Django 6.0.2 on 2026-03-26 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_alter_gallerypage_features_alter_homepage_activities_and_more'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='bg_additional_video_size_l',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='wagtaildocs.document', verbose_name='Дополнительное фоновое видео (большое) 1980x1080'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='bg_additional_video_size_m',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Дополнительное фоновое видео (среднее) 1280x800'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='bg_additional_video_size_s',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Дополнительное фоновое видео (малое) 480x800'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='bg_video_size_l',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='wagtaildocs.document', verbose_name='Фоновое видео (большое) 1980x1080'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='bg_video_size_m',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Фоновое видео (среднее) 1280x800'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='bg_video_size_s',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Фоновое видео (малое) 480x800'),
        ),
    ]
