# Generated by Django 6.0.2 on 2026-08-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_homepage_bg_additional_video_size_l_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roompage',
            name='beds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество спальных мест'),
        ),
        migrations.AlterField(
            model_name='roompage',
            name='children',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество детей'),
        ),
        migrations.AlterField(
            model_name='roompage',
            name='room_size',
            field=models.TextField(blank=True, help_text='Пример: 14-20м2', null=True, verbose_name='Размер номера'),
        ),
    ]
