# Generated by Django 6.0.2 on 2026-08-11 06:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_roompage_additional_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericsettings',
            name='room_global_features_1',
            field=wagtail.fields.StreamField([('feature', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 255}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: fa-bed, fa-wifi. https://fontawesome.com/search?q=cat&ic=free-collection', 'label': 'Иконка', 'max_length': 50, 'required': False}), 2: ('wagtail.blocks.FloatBlock', (), {'label': 'Счетчик', 'max_length': 255, 'min_value': 0, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('text', 0), ('icon', 1), ('counter', 2)]], {'label': 'Особенность'})}, verbose_name='Удобства и услуги'),
        ),
    ]
